name: Setup
description: Setup Build Step
inputs:
  node-version:
    required: true
    default: '18.x'

runs:
  using: "composite"
  steps:
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        cache: yarn

    - name: Install dependencies
      shell: bash
      run: yarn install
