name: Setup
description: Setup Build Step

runs:
  using: "composite"
  steps:
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: .node-version
        cache: yarn

    - name: Install dependencies
      shell: bash
      run: yarn install
