name: Setup
description: Setup Build Step

runs:
  using: "composite"
  steps:
    # v6.4.0
    - name: Use Node.js
      uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e
      with:
        node-version-file: .node-version

    - name: Enable Corepack
      shell: bash
      run: corepack enable

    - name: Install dependencies
      shell: bash
      run: yarn install --immutable
