/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docsSidebar: [
    "introduction",
    "getting-started",
    {
      type: "category",
      label: "Cartesian Charts",
      collapsed: false,
      collapsible: false,
      items: [
        "cartesian/cartesian-chart",
        "cartesian/chart-gestures",

        {
          type: "category",
          label: "Guides",
          items: [
            "cartesian/guides/basic-bar-chart",
            "cartesian/guides/multi-press",
          ],
        },

        {
          type: "category",
          label: "Line Paths",
          items: ["cartesian/line/line", "cartesian/line/use-line-path"],
        },
        {
          type: "category",
          label: "Area Paths",
          items: ["cartesian/area/area", "cartesian/area/use-area-path"],
        },
        {
          type: "category",
          label: "Bar Paths",
          items: [
            "cartesian/bar/bar",
            "cartesian/bar/use-bar-path",
            "cartesian/bar/bar-group",
            "cartesian/bar/use-bar-group-paths",
          ],
        },
        {
          type: "category",
          label: "Scatter Paths",
          items: ["cartesian/scatter/scatter"],
        },
      ],
    },
    {
      type: "category",
      label: "Pie Charts",
      collapsed: false,
      collapsible: false,
      items: [
        "pie/pie-charts",
        {
          type: "category",
          label: "Legends",
          items: ["pie/pie-chart-legend", "pie/pie-chart-legend-item"],
        },
        "pie/use-slice-path",
        "pie/use-slice-angular-inset-path",
      ],
    },

    "animated-paths",
  ],
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{ type: "autogenerated", dirName: "." }],
};

module.exports = sidebars;
