// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docsSidebar: [
    "introduction",
    "getting-started",
    "cartesian-chart",
    {
      type: "category",
      label: "Line Paths",
      items: ["line/use-line-path", "line/line"],
    },
    {
      type: "category",
      label: "Area Paths",
      items: ["area/use-area-path", "area/area"],
    },
  ],
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{ type: "autogenerated", dirName: "." }],
};

module.exports = sidebars;
