// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docsSidebar: [
    "introduction",
    "getting-started",
    "cartesian-chart",
    {
      type: "category",
      label: "Guides",
      items: ["guides/basic-bar-chart"],
    },
    {
      type: "category",
      label: "Line Paths",
      items: ["line/line", "line/use-line-path"],
    },
    {
      type: "category",
      label: "Area Paths",
      items: ["area/area", "area/use-area-path"],
    },
    {
      type: "category",
      label: "Bar Paths",
      items: [
        "bar/bar",
        "bar/use-bar-path",
        "bar/bar-group",
        "bar/use-bar-group-paths",
      ],
    },
    {
      type: "category",
      label: "Scatter Paths",
      items: ["scatter/scatter"],
    },
    "animated-paths",
  ],
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{ type: "autogenerated", dirName: "." }],
};

module.exports = sidebars;
