name: Code Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # v6.0.2
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - uses: ./.github/actions/setup

      - name: Lint
        run: yarn run lint

      - name: Typecheck
        run: yarn run typecheck

      - name: Unit Test
        run: yarn run test
