name: Victory Native Release Workflow

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      issues: write
      repository-projects: write
      deployments: write
      packages: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup

      - name: Build
        run: yarn run build

      - name: PR or Publish
        id: changesets
        uses: changesets/action@v1
        with:
          version: yarn run version
          publish: yarn run changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
